version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile_web
    container_name: web
    environment: 
      DB_HOST: db
      DB_USER: whoknows
      DB_PASSWD: 123456
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aBzai6@A
      MYSQL_DATABASE: whoknows
      MYSQL_USER: whoknows
      MYSQL_PASSWORD: 123456
  
  poc:
    build: 
      context: .
      dockerfile: Dockerfile_poc
    container_name: poc
    ports: 
      - "80:80"
    depends_on:
      - db
      - web
